# Generated by Django 3.1 on 2020-09-07 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_hour', models.CharField(blank=True, choices=[('12:00 AM', '12:00 AM'), ('01:00 AM', '01:00 AM'), ('02:00 AM', '02:00 AM'), ('03:00 AM', '03:00 AM'), ('04:00 AM', '04:00 AM'), ('05:00 AM', '05:00 AM'), ('06:00 AM', '06:00 AM'), ('07:00 AM', '07:00 AM'), ('08:00 AM', '08:00 AM'), ('09:00 AM', '09:00 AM'), ('10:00 AM', '10:00 AM'), ('11:00 AM', '11:00 AM'), ('12:00 PM', '12:00 PM'), ('01:00 PM', '01:00 PM'), ('02:00 PM', '02:00 PM'), ('03:00 PM', '03:00 PM'), ('04:00 PM', '04:00 PM'), ('05:00 PM', '05:00 PM'), ('06:00 PM', '06:00 PM'), ('07:00 PM', '07:00 PM'), ('08:00 PM', '08:00 PM'), ('09:00 PM', '09:00 PM'), ('10:00 PM', '10:00 PM'), ('11:00 PM', '11:00 PM')], default='05:00 AM', max_length=8, null=True)),
                ('default_Week_start_day', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
