# Generated by Django 3.1 on 2020-09-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200905_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='default_Week_start_day',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='default_year',
            field=models.CharField(blank=True, choices=[(2020, 2020), (2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011)], default=2020, max_length=4, null=True),
        ),
    ]
