# Generated by Django 3.1 on 2020-09-05 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200905_1649'),
    ]

    operations = [
    ]
