# Generated by Django 3.1 on 2020-08-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='S1902000403',
            fields=[
                ('srl', models.AutoField(db_column='SRL', primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(db_column='DATE_TIME')),
                ('volt1', models.SmallIntegerField(blank=True, db_column='Volt1', null=True)),
                ('amp1', models.SmallIntegerField(blank=True, db_column='Amp1', null=True)),
                ('kw1', models.SmallIntegerField(blank=True, db_column='Kw1', null=True)),
                ('pf1', models.SmallIntegerField(blank=True, db_column='PF1', null=True)),
                ('kvar1', models.SmallIntegerField(blank=True, db_column='KVAr1', null=True)),
                ('kva1', models.SmallIntegerField(blank=True, db_column='KVA1', null=True)),
                ('clo1', models.IntegerField(blank=True, db_column='CLO1', null=True)),
                ('rct1', models.IntegerField(blank=True, db_column='RCT1', null=True)),
                ('volt2', models.SmallIntegerField(blank=True, db_column='Volt2', null=True)),
                ('amp2', models.SmallIntegerField(blank=True, db_column='Amp2', null=True)),
                ('kw2', models.SmallIntegerField(blank=True, db_column='Kw2', null=True)),
                ('pf2', models.SmallIntegerField(blank=True, db_column='PF2', null=True)),
                ('kvar2', models.SmallIntegerField(blank=True, db_column='KVAr2', null=True)),
                ('kva2', models.SmallIntegerField(blank=True, db_column='KVA2', null=True)),
                ('clo2', models.IntegerField(blank=True, db_column='CLO2', null=True)),
                ('rct2', models.IntegerField(blank=True, db_column='RCT2', null=True)),
                ('volt3', models.SmallIntegerField(blank=True, db_column='Volt3', null=True)),
                ('amp3', models.SmallIntegerField(blank=True, db_column='Amp3', null=True)),
                ('kw3', models.SmallIntegerField(blank=True, db_column='Kw3', null=True)),
                ('pf3', models.SmallIntegerField(blank=True, db_column='PF3', null=True)),
                ('kvar3', models.SmallIntegerField(blank=True, db_column='KVAr3', null=True)),
                ('kva3', models.SmallIntegerField(blank=True, db_column='KVA3', null=True)),
                ('clo3', models.IntegerField(blank=True, db_column='CLO3', null=True)),
                ('rct3', models.IntegerField(blank=True, db_column='RCT3', null=True)),
                ('cap1', models.IntegerField(blank=True, db_column='CAP1', null=True)),
                ('cap2', models.IntegerField(blank=True, db_column='CAP2', null=True)),
                ('cap3', models.IntegerField(blank=True, db_column='CAP3', null=True)),
                ('cap4', models.IntegerField(blank=True, db_column='CAP4', null=True)),
                ('cap5', models.IntegerField(blank=True, db_column='CAP5', null=True)),
                ('cap6', models.IntegerField(blank=True, db_column='CAP6', null=True)),
                ('cap7', models.IntegerField(blank=True, db_column='CAP7', null=True)),
                ('cap8', models.IntegerField(blank=True, db_column='CAP8', null=True)),
                ('cap9', models.IntegerField(blank=True, db_column='CAP9', null=True)),
                ('cap10', models.IntegerField(blank=True, db_column='CAP10', null=True)),
                ('cap11', models.IntegerField(blank=True, db_column='CAP11', null=True)),
                ('cap12', models.IntegerField(blank=True, db_column='CAP12', null=True)),
            ],
            options={
                'db_table': 'S_19020004_03',
                'get_latest_by': 'srl',
            },
        ),
    ]
