# Generated by Django 3.1 on 2020-09-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ermapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('saving', models.IntegerField()),
                ('usage', models.IntegerField()),
                ('energy', models.IntegerField()),
                ('power_factor', models.IntegerField()),
                ('thd', models.IntegerField()),
                ('tdi', models.IntegerField()),
            ],
        ),
    ]
