# Generated by Django 3.1 on 2020-09-05 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ermapp', '0002_dashboardtable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardtable',
            options={'get_latest_by': 'id', 'ordering': ['-date_time']},
        ),
    ]
